# Generated by Django 4.2.1 on 2023-06-03 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("personas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstadoPrestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "estados_prestamo",
            },
        ),
        migrations.CreateModel(
            name="TipoPrestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "tipos_prestamo",
            },
        ),
        migrations.CreateModel(
            name="Prestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nro_prestamo", models.CharField(max_length=10)),
                ("fecha", models.DateField()),
                ("capital", models.DecimalField(decimal_places=2, max_digits=12)),
                ("interes", models.FloatField()),
                ("plazo", models.IntegerField()),
                ("fecha_inicio", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "estado_prestamo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="prestamos.estadoprestamo",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="personas.persona",
                    ),
                ),
                (
                    "tipo_prestamo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="prestamos.tipoprestamo",
                    ),
                ),
            ],
            options={
                "db_table": "prestamos",
            },
        ),
        migrations.CreateModel(
            name="CuotaPrestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nro_cuota", models.IntegerField()),
                ("fecha_vencimiento", models.DateField()),
                ("monto_cuota", models.DecimalField(decimal_places=2, max_digits=9)),
                ("monto_interes", models.DecimalField(decimal_places=2, max_digits=9)),
                ("saldo_cuota", models.DecimalField(decimal_places=2, max_digits=12)),
                ("saldo_interes", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "prestamo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="prestamos.prestamo",
                    ),
                ),
            ],
            options={
                "db_table": "cuotas_prestamo",
            },
        ),
    ]
