# Generated by Django 4.2.1 on 2023-06-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prestamos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuotaprestamo",
            name="monto_capital",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="cuotaprestamo",
            name="saldo_capital",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="cuotaprestamo",
            name="monto_cuota",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="cuotaprestamo",
            name="monto_interes",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="cuotaprestamo",
            name="saldo_cuota",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="cuotaprestamo",
            name="saldo_interes",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
