# Generated by Django 4.2.1 on 2023-06-17 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("personas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("prestamos", "0002_cuotaprestamo_monto_capital_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrecuenciaPagoPrestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=20)),
                (
                    "tasas_efectivas",
                    models.DecimalField(decimal_places=10, max_digits=12),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "frecuencias_pago_prestamo",
            },
        ),
        migrations.CreateModel(
            name="SistemaPrestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=10)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "sistemas_prestamo",
            },
        ),
        migrations.AddField(
            model_name="estadoprestamo",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="prestamo",
            name="modified_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="prestamo",
            name="modified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="modified_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tipoprestamo",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="prestamo",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="prestamo",
            name="persona",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="personas.persona",
            ),
        ),
        migrations.AlterField(
            model_name="prestamo",
            name="tipo_prestamo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="prestamos.tipoprestamo",
            ),
        ),
        migrations.AddField(
            model_name="prestamo",
            name="frecuencia",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="prestamos.frecuenciapagoprestamo",
            ),
        ),
        migrations.AddField(
            model_name="prestamo",
            name="sistema_prestamo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="prestamos.sistemaprestamo",
            ),
        ),
    ]
