# Generated by Django 4.2.1 on 2023-06-17 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prestamos", "0003_frecuenciapagoprestamo_sistemaprestamo_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="frecuenciapagoprestamo",
            table="frecuencias_pago",
        ),
    ]
