# Generated by Django 4.2.1 on 2023-06-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prestamos", "0006_alter_prestamo_created_at_alter_prestamo_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuotaprestamo",
            name="fecha_ultimo_pago",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="prestamo",
            name="created_at",
            field=models.DateTimeField(null=True),
        ),
    ]
