# Generated by Django 4.2.1 on 2023-06-24 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prestamos", "0007_cuotaprestamo_fecha_ultimo_pago_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prestamo",
            old_name="fecha_inicio",
            new_name="fecha_primer_vencimiento",
        ),
    ]
