# Generated by Django 4.2.1 on 2023-06-25 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "prestamos",
            "0009_alter_prestamo_created_at_alter_prestamo_created_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="prestamo",
            name="created_by",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="prestamo",
            name="modified_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="prestamo",
            name="modified_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="modified_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="prestamo",
            name="nro_prestamo",
            field=models.IntegerField(editable=False),
        ),
    ]
