# Generated by Django 4.2.1 on 2023-07-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "prestamos",
            "0010_alter_prestamo_created_by_alter_prestamo_modified_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EstadoCuentaPrestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("persona_id", models.IntegerField()),
                ("nro_prestamo", models.IntegerField()),
                ("fecha", models.DateField()),
                ("nro_cuota", models.IntegerField()),
                ("fecha_vencimiento", models.DateField()),
                ("monto_cuota", models.DecimalField(decimal_places=0, max_digits=10)),
                ("saldo_cuota", models.DecimalField(decimal_places=0, max_digits=10)),
                ("fecha_pago", models.DateField()),
                ("cuota_actual_total", models.CharField(max_length=20)),
                ("monto_pago", models.DecimalField(decimal_places=0, max_digits=10)),
                (
                    "acumulado_pago",
                    models.DecimalField(decimal_places=0, max_digits=10),
                ),
                ("saldo_actual", models.DecimalField(decimal_places=0, max_digits=10)),
                ("nro_pago", models.IntegerField()),
            ],
            options={
                "db_table": "vw_estado_cuenta_prestamos",
                "managed": False,
            },
        ),
    ]
