# Generated by Django 4.2.1 on 2023-08-12 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("suscripciones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistorialPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=0, max_digits=12)),
                ("fecha_pago", models.DateField()),
                (
                    "suscripcion",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="suscripciones.suscripcion",
                    ),
                ),
            ],
            options={
                "db_table": "historial_pagos",
            },
        ),
    ]
