# Generated by Django 4.2.1 on 2023-08-12 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0001_initial"),
        ("unidades_medidas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversionMedida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operacion",
                    models.CharField(
                        choices=[
                            ("Multiplica", "MULTIPLICA"),
                            ("Divide", "DIVIDE"),
                            ("Potencia", "POTENCIA"),
                        ],
                        max_length=20,
                    ),
                ),
                ("valor", models.FloatField()),
                ("activo", models.BooleanField(default=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="empresas.empresa",
                    ),
                ),
                (
                    "medida_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medida_a",
                        to="unidades_medidas.unidadmedida",
                    ),
                ),
                (
                    "medida_de",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medida_de",
                        to="unidades_medidas.unidadmedida",
                    ),
                ),
            ],
            options={
                "db_table": "conversiones_medidas",
            },
        ),
    ]
