# Generated by Django 4.2.1 on 2023-08-12 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("apellido", models.CharField(max_length=100)),
                ("razon_social", models.CharField(max_length=200)),
                ("fecha_nacimiento", models.DateField(null=True)),
                ("es_cliente", models.BooleanField(default=False)),
                ("es_proveedor", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "personas",
            },
        ),
        migrations.CreateModel(
            name="Sexo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "sexos",
            },
        ),
        migrations.CreateModel(
            name="TipoDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=100)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "tipos_documentos",
            },
        ),
        migrations.CreateModel(
            name="TipoPersona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=50)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "tipos_personas",
            },
        ),
        migrations.CreateModel(
            name="Telefono",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=100)),
                ("por_defecto", models.BooleanField(default=False)),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="personas.persona",
                    ),
                ),
            ],
            options={
                "db_table": "telefonos",
            },
        ),
        migrations.AddField(
            model_name="persona",
            name="sexo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="personas.sexo",
            ),
        ),
        migrations.AddField(
            model_name="persona",
            name="tipo_persona",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="personas.tipopersona",
            ),
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=30, unique=True)),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="personas.persona",
                    ),
                ),
                (
                    "tipo_documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="personas.tipodocumento",
                    ),
                ),
            ],
            options={
                "db_table": "documentos",
            },
        ),
        migrations.CreateModel(
            name="Direccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=100)),
                ("por_defecto", models.BooleanField(default=False)),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="personas.persona",
                    ),
                ),
            ],
            options={
                "db_table": "direcciones",
            },
        ),
    ]
