# Generated by Django 4.2.1 on 2023-07-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagares", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagare",
            name="direccion_co_deudor",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="pagare",
            name="documento_co_deudor",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="pagare",
            name="nombre_co_deudor",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
