# Generated by Django 4.2.1 on 2023-08-12 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ciudades", "0001_initial"),
        ("departamentos", "0001_initial"),
        ("empresas", "0001_initial"),
        ("paises", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sucursal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=80)),
                ("direccion", models.CharField(max_length=80)),
                ("telefono", models.CharField(max_length=20)),
                ("activo", models.BooleanField(default=True)),
                (
                    "ciudad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ciudades.ciudad",
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="departamentos.departamento",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="empresas.empresa",
                    ),
                ),
                (
                    "pais",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="paises.pais"
                    ),
                ),
            ],
            options={
                "db_table": "sucursales",
            },
        ),
    ]
