# Generated by Django 4.2.1 on 2023-08-12 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0001_initial"),
        ("depositos", "0001_initial"),
        ("lotes", "0001_initial"),
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovimientoProductoLote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("saldo_anterior", models.FloatField()),
                ("cantidad_entrada", models.FloatField()),
                ("cantidad_salida", models.FloatField()),
                ("saldo_actual", models.FloatField()),
                (
                    "deposito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="depositos.deposito",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="empresas.empresa",
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="lotes.lote"
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="productos.producto",
                    ),
                ),
            ],
            options={
                "db_table": "movimientos_productos_lotes",
            },
        ),
        migrations.CreateModel(
            name="MovimientoProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("saldo_anterior", models.FloatField()),
                ("cantidad_entrada", models.FloatField()),
                ("cantidad_salida", models.FloatField()),
                ("saldo_actual", models.FloatField()),
                (
                    "deposito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="depositos.deposito",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="empresas.empresa",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="productos.producto",
                    ),
                ),
            ],
            options={
                "db_table": "movimientos_productos",
            },
        ),
    ]
