# Generated by Django 4.2.1 on 2023-08-12 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("personas", "0001_initial"),
        ("prestamos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pagare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto_pagare", models.DecimalField(decimal_places=0, max_digits=12)),
                ("fecha_emision", models.DateField()),
                ("fecha_vencimiento", models.DateField()),
                ("nombre_co_deudor", models.CharField(max_length=100, null=True)),
                ("documento_co_deudor", models.CharField(max_length=20, null=True)),
                ("direccion_co_deudor", models.CharField(max_length=100, null=True)),
                (
                    "cuota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="prestamos.cuotaprestamo",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="personas.persona",
                    ),
                ),
            ],
            options={
                "db_table": "pagares",
            },
        ),
    ]
