# Generated by Django 4.2.1 on 2023-08-12 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0001_initial"),
        ("personas", "0001_initial"),
        ("tipos_movimientos", "0001_initial"),
        ("sucursales", "0001_initial"),
        ("monedas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("nro_documento", models.CharField(max_length=20)),
                ("monto_total", models.FloatField()),
                ("monto_grav10", models.FloatField()),
                ("monto_grav5", models.FloatField()),
                ("monto_iva10", models.FloatField()),
                ("monto_iva5", models.FloatField()),
                ("monto_exento", models.FloatField()),
                ("tasa_cambio", models.FloatField()),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="personas.persona",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="empresas.empresa",
                    ),
                ),
                (
                    "moneda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="monedas.moneda"
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sucursales.sucursal",
                    ),
                ),
                (
                    "tipo_movimiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tipos_movimientos.tipomovimiento",
                    ),
                ),
            ],
            options={
                "db_table": "movimientos",
            },
        ),
    ]
