# Generated by Django 4.2.1 on 2023-08-12 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("personas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstadoCuentaPrestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("persona_id", models.IntegerField()),
                ("nro_prestamo", models.IntegerField()),
                ("fecha", models.DateField()),
                ("nro_cuota", models.IntegerField()),
                ("fecha_vencimiento", models.DateField()),
                ("monto_cuota", models.DecimalField(decimal_places=0, max_digits=10)),
                ("saldo_cuota", models.DecimalField(decimal_places=0, max_digits=10)),
                ("fecha_pago", models.DateField()),
                ("cuota_actual_total", models.CharField(max_length=20)),
                ("monto_pago", models.DecimalField(decimal_places=0, max_digits=10)),
                (
                    "acumulado_pago",
                    models.DecimalField(decimal_places=0, max_digits=10),
                ),
                ("saldo_actual", models.DecimalField(decimal_places=0, max_digits=10)),
                ("nro_pago", models.IntegerField()),
            ],
            options={
                "db_table": "vw_estado_cuenta_prestamos",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EstadoPrestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=20)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "estados_prestamo",
            },
        ),
        migrations.CreateModel(
            name="FrecuenciaPagoPrestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=20)),
                (
                    "tasas_efectivas",
                    models.DecimalField(decimal_places=10, max_digits=12),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "frecuencias_pago",
            },
        ),
        migrations.CreateModel(
            name="SistemaPrestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=50)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "sistemas_prestamo",
            },
        ),
        migrations.CreateModel(
            name="TipoPrestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=50)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "tipos_prestamo",
            },
        ),
        migrations.CreateModel(
            name="Prestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nro_prestamo", models.IntegerField(editable=False)),
                ("fecha", models.DateField()),
                ("capital", models.DecimalField(decimal_places=0, max_digits=12)),
                ("interes", models.FloatField()),
                ("plazo", models.IntegerField()),
                ("fecha_primer_vencimiento", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(editable=False, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "estado_prestamo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="prestamos.estadoprestamo",
                    ),
                ),
                (
                    "frecuencia",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="prestamos.frecuenciapagoprestamo",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="personas.persona",
                    ),
                ),
                (
                    "sistema_prestamo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="prestamos.sistemaprestamo",
                    ),
                ),
                (
                    "tipo_prestamo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="prestamos.tipoprestamo",
                    ),
                ),
            ],
            options={
                "db_table": "prestamos",
            },
        ),
        migrations.CreateModel(
            name="CuotaPrestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nro_cuota", models.IntegerField()),
                ("fecha_vencimiento", models.DateField()),
                (
                    "monto_cuota",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "monto_interes",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "monto_capital",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "saldo_cuota",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "saldo_capital",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "saldo_interes",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                ("fecha_ultimo_pago", models.DateField(null=True)),
                (
                    "prestamo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="prestamos.prestamo",
                    ),
                ),
            ],
            options={
                "db_table": "cuotas_prestamo",
            },
        ),
    ]
