# Generated by Django 4.2.1 on 2023-08-12 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0001_initial"),
        ("sucursales", "0001_initial"),
        ("prestamos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuotaprestamo",
            name="empresa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="empresas.empresa",
            ),
        ),
        migrations.AddField(
            model_name="estadoprestamo",
            name="empresa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="empresas.empresa",
            ),
        ),
        migrations.AddField(
            model_name="frecuenciapagoprestamo",
            name="empresa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="empresas.empresa",
            ),
        ),
        migrations.AddField(
            model_name="prestamo",
            name="empresa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="empresas.empresa",
            ),
        ),
        migrations.AddField(
            model_name="prestamo",
            name="sucursal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="sucursales.sucursal",
            ),
        ),
        migrations.AddField(
            model_name="sistemaprestamo",
            name="empresa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="empresas.empresa",
            ),
        ),
        migrations.AddField(
            model_name="tipoprestamo",
            name="empresa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="empresas.empresa",
            ),
        ),
        migrations.AlterModelTable(
            name="frecuenciapagoprestamo",
            table="frecuencias_pagos",
        ),
    ]
