# Generated by Django 4.2.1 on 2023-08-12 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0001_initial"),
        ("tipos_productos", "0001_initial"),
        ("clases_productos", "0001_initial"),
        ("impuestos", "0001_initial"),
        ("unidades_medidas", "0001_initial"),
        ("grupos", "0001_initial"),
        ("familias", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=80)),
                ("controla_lote", models.BooleanField(default=False)),
                ("controla_existencia", models.BooleanField(default=True)),
                ("codigo_fabrica", models.CharField(max_length=30, null=True)),
                ("codigo_barra", models.CharField(max_length=30, null=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "clase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="clases_productos.claseproducto",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="empresas.empresa",
                    ),
                ),
                (
                    "familia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="familias.familiaproducto",
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="grupos.grupoproducto",
                    ),
                ),
                (
                    "impuesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="impuestos.impuesto",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tipos_productos.tipoproducto",
                    ),
                ),
                (
                    "unidad_medida",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="unidades_medidas.unidadmedida",
                    ),
                ),
            ],
            options={
                "db_table": "productos",
            },
        ),
    ]
