# Generated by Django 4.2.1 on 2023-08-12 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0001_initial"),
        ("tipos_comprobantes", "0001_initial"),
        ("operaciones_stock", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoMovimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=50)),
                (
                    "afecta_saldo",
                    models.CharField(
                        choices=[
                            ("No afecta", "NINGUNO"),
                            ("Débito", "DEBE"),
                            ("Crédito", "HABER"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="empresas.empresa",
                    ),
                ),
                (
                    "operacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="operaciones_stock.operacionstock",
                    ),
                ),
                (
                    "tipo_comprobante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tipos_comprobantes.tipocomprobante",
                    ),
                ),
            ],
            options={
                "db_table": "tipos_movimientos",
            },
        ),
    ]
