# Generated by Django 4.2.1 on 2023-06-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="persona",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="persona",
            name="fecha_nacimiento",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="tipopersona",
            name="activo",
            field=models.BooleanField(default=True),
        ),
    ]
